export const AUTH_STARTED = "AUTH_STARTED";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";

export const VERIFY_EMAIL_STARTED = "VERIFY_EMAIL_STARTED";
export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_FAILED = "VERIFY_EMAIL_FAILED";

export const LOGOUT = "LOGOUT";

export const CLEAN = "CLEAN";

export const ADD_REMINDER_STARTED = "ADD_REMINDER_STARTED";
export const ADD_REMINDER_SUCCESS = "ADD_REMINDER_SUCCESS";
export const ADD_REMINDER_FAILED = "ADD_REMINDER_FAILED";
